version: "3.3"

services:
  postservice-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'postservice_db'
      MYSQL_USER: 'cloudpxl'
      MYSQL_PASSWORD: 'cloudpxl'
      MYSQL_ROOT_PASSWORD: 'root'

  reviewservice-db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'reviewservice_db'
      MYSQL_USER: 'cloudpxl'
      MYSQL_PASSWORD: 'cloudpxl'
      MYSQL_ROOT_PASSWORD: 'root'

  commentservice-db:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: 'commentservice_db'
      MYSQL_USER: 'cloudpxl'
      MYSQL_PASSWORD: 'cloudpxl'
      MYSQL_ROOT_PASSWORD: 'root'

